[server]
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#111827"
textColor = "#F1F5F9"
font = "sans serif"

